### ISSUE TITLE
Change Right Click to ignore Crouching Right Click

### ISSUE THREAD

**Issue by Peashooter101** [Simplexity-Development/Scythe#1]
## Problem

Currently, the plugin harvests on right click shift, which is generally used to "ignore" typical right click actions.

## Suggestion

Ignore any right clicks on plants that are done using a crouching right click to allow for consistency and so I can actually place a block against the side of this wheat seed.

![image](https://user-images.githubusercontent.com/20095065/210887300-1169339c-bd0b-4cc9-8ce9-b3c59792f8a8.png)

**Comment by RhythmicSys** [comment]
Better solution: The plugin will now just, return  on interaction instead of cancelling. Only cancels breaking now if the crop isn't full grown
