### ISSUE TITLE
Cannot Remove Existing Crops.

### ISSUE THREAD

**Issue by Peashooter101** [Simplexity-Development/Scythe#2]
## Problem

Existing crops, such as newly planted wheat seeds, cannot be broken to remove them, every break will replant them. The block below them has to be removed or the crop has to be trampled, or some other non-standard way to break the seeds.

This specifically was tested on Wheat, Carrot, Potato, Nether Wart.

## Suggestion

If the crop is not matured, do not automatically replant.

**Comment by RhythmicSys** [comment]
The reason this exists as it does, is because very often the client will just end up breaking the new crop.
the way to avoid this is by using `/scythe toggle` to turn off the feature, or by requiring hoes in the config
